<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Predicting Exam Scores</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="DW_Final_files/libs/clipboard/clipboard.min.js"></script>
<script src="DW_Final_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="DW_Final_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="DW_Final_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="DW_Final_files/libs/quarto-html/popper.min.js"></script>
<script src="DW_Final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="DW_Final_files/libs/quarto-html/anchor.min.js"></script>
<link href="DW_Final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="DW_Final_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="DW_Final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="DW_Final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="DW_Final_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Exam Scores</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>As I head into finals this week, I wanted to look into the factors that impact college students’ success on exams. I first want to visualize metrics that I think would have a significant impact on a students exam score to start understanding variable signficance. From there, I would like to quantify their relationships through the means of an OLS model. Finally, I want to see if I can predict a students exam score using Random Forrest Regression.</p>
<p>Through this analysis I hope to understand:</p>
<ol type="1">
<li><p>What factors most strongly influence a students exam performance, and therefore what should I prioritize this week?</p></li>
<li><p>Can we predict exam score based off the available data?</p></li>
</ol>
</section>
<section id="purpose" class="level2">
<h2 class="anchored" data-anchor-id="purpose">Purpose</h2>
<p>Understanding which variables influence exam performance can help students prioritize specific behaviors when aiming for educational success. For example, if tutoring is not strongly associated with higher exam scores, students may choose prioritize attendance or sleep to improve their performance. Additionally, accurately being able to predict exam score performance could be immensely useful to professors. If they calculate that a student should earn a 90 but they recieve a 65, there may have been an error when grading or they can speak to the student to understand if something went wrong.</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>The data I used for the project includes a variety of information about students, their education, and behaviors. Variables included are both numeric and categorical. Some metrics of importance include hours studied, attendance hours, resource availability, and family income.</p>
<div id="833d2876" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="900e5039" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_csv(<span class="st">"/Users/maddypitman/Downloads/StudentPerformanceFactors.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Hours_Studied</th>
<th data-quarto-table-cell-role="th">Attendance</th>
<th data-quarto-table-cell-role="th">Parental_Involvement</th>
<th data-quarto-table-cell-role="th">Access_to_Resources</th>
<th data-quarto-table-cell-role="th">Extracurricular_Activities</th>
<th data-quarto-table-cell-role="th">Sleep_Hours</th>
<th data-quarto-table-cell-role="th">Previous_Scores</th>
<th data-quarto-table-cell-role="th">Motivation_Level</th>
<th data-quarto-table-cell-role="th">Internet_Access</th>
<th data-quarto-table-cell-role="th">Tutoring_Sessions</th>
<th data-quarto-table-cell-role="th">Family_Income</th>
<th data-quarto-table-cell-role="th">Teacher_Quality</th>
<th data-quarto-table-cell-role="th">School_Type</th>
<th data-quarto-table-cell-role="th">Peer_Influence</th>
<th data-quarto-table-cell-role="th">Physical_Activity</th>
<th data-quarto-table-cell-role="th">Learning_Disabilities</th>
<th data-quarto-table-cell-role="th">Parental_Education_Level</th>
<th data-quarto-table-cell-role="th">Distance_from_Home</th>
<th data-quarto-table-cell-role="th">Gender</th>
<th data-quarto-table-cell-role="th">Exam_Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>23</td>
<td>84</td>
<td>Low</td>
<td>High</td>
<td>No</td>
<td>7</td>
<td>73</td>
<td>Low</td>
<td>Yes</td>
<td>0</td>
<td>Low</td>
<td>Medium</td>
<td>Public</td>
<td>Positive</td>
<td>3</td>
<td>No</td>
<td>High School</td>
<td>Near</td>
<td>Male</td>
<td>67</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>19</td>
<td>64</td>
<td>Low</td>
<td>Medium</td>
<td>No</td>
<td>8</td>
<td>59</td>
<td>Low</td>
<td>Yes</td>
<td>2</td>
<td>Medium</td>
<td>Medium</td>
<td>Public</td>
<td>Negative</td>
<td>4</td>
<td>No</td>
<td>College</td>
<td>Moderate</td>
<td>Female</td>
<td>61</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>24</td>
<td>98</td>
<td>Medium</td>
<td>Medium</td>
<td>Yes</td>
<td>7</td>
<td>91</td>
<td>Medium</td>
<td>Yes</td>
<td>2</td>
<td>Medium</td>
<td>Medium</td>
<td>Public</td>
<td>Neutral</td>
<td>4</td>
<td>No</td>
<td>Postgraduate</td>
<td>Near</td>
<td>Male</td>
<td>74</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>29</td>
<td>89</td>
<td>Low</td>
<td>Medium</td>
<td>Yes</td>
<td>8</td>
<td>98</td>
<td>Medium</td>
<td>Yes</td>
<td>1</td>
<td>Medium</td>
<td>Medium</td>
<td>Public</td>
<td>Negative</td>
<td>4</td>
<td>No</td>
<td>High School</td>
<td>Moderate</td>
<td>Male</td>
<td>71</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>19</td>
<td>92</td>
<td>Medium</td>
<td>Medium</td>
<td>Yes</td>
<td>6</td>
<td>65</td>
<td>Medium</td>
<td>Yes</td>
<td>3</td>
<td>Medium</td>
<td>High</td>
<td>Public</td>
<td>Neutral</td>
<td>4</td>
<td>No</td>
<td>College</td>
<td>Near</td>
<td>Female</td>
<td>70</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="exploring-the-data-what-factors-seem-to-be-most-closely-related-to-exam-perfromance" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data-what-factors-seem-to-be-most-closely-related-to-exam-perfromance">Exploring the Data: What factors seem to be most closely related to exam perfromance?</h2>
<div id="48475cbc" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>plt.scatter(data[<span class="st">'Hours_Studied'</span>], data[<span class="st">'Exam_Score'</span>])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DW_Final_files/figure-html/cell-4-output-1.png" width="575" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>I plotted a scatterplot to analyze the relationship between the hours a student studied and their exam score. This is the best choice to evaluate strength and direction of two continuous variables.</p>
<p>I would think study hours would be one of the greatest predictors of exam success. While there is a general upward trend, there are also many outliers that seem to do well regardless of their study time. This can likely be attributed to natural ability.</p>
<div id="56bef523" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>,<span class="dv">4</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>sns.boxplot(data<span class="op">=</span>data, x<span class="op">=</span><span class="st">'School_Type'</span>, y<span class="op">=</span><span class="st">'Exam_Score'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'School Type'</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Exam Score'</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Exam Score Distribution: Public vs Private Schools'</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DW_Final_files/figure-html/cell-5-output-1.png" width="519" height="376" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Next, I wanted to compare the spread of exam scores by private and public schools. A boxplot using matplotlib was the most clear way to accomplish this.</p>
<p>Exam scores to not appear to differ tremendously by Education Type. The average score for both education types is around a 68. Both school types also have outliers with similar ranges. This could be an interesting factor to consider when looking at tuition costs and evaluating differences in quality of eduction.</p>
<div id="31d4c596" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>plt.scatter(data[<span class="st">'Attendance'</span>], data[<span class="st">'Exam_Score'</span>])</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DW_Final_files/figure-html/cell-6-output-1.png" width="575" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Attendance seems like it would also help predict a students exam score. To explore the relationship a a scatterplot was the right choice for the continuous variables.</p>
<p>Attendance has a similar relationship to exam scores as study hours. There is an upward trend present, however, there are a fair amount of students that perfrom well regardless of the hours of school they attend.</p>
<div id="722cafc3" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>,<span class="dv">4</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>sns.boxplot(data<span class="op">=</span>data, x<span class="op">=</span><span class="st">'Sleep_Hours'</span>, y<span class="op">=</span><span class="st">'Exam_Score'</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Houes of Sleep'</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Exam Score'</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Exam Score Distribution: Sleep Hours'</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DW_Final_files/figure-html/cell-7-output-1.png" width="519" height="376" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Finally, I wanted to see if exam scores differ for student who get different amounts of sleep. Since sleep is categorical in the sense that there are only a few options, it made sense to use a boxplot.</p>
<p>Different hours of sleep do not impact scores obtained by students. The average scores and spreads are no differnt across differnt amounts of sleep. Normally I prioritize going to sleep extremely early if I have an exam the next day but this data suggests that may not be the best tactic.</p>
</section>
<section id="modeling" class="level2">
<h2 class="anchored" data-anchor-id="modeling">Modeling</h2>
<p>I will be using OLS from statsmodels.formula.api to quantify the relationship between the predictive variables and exam score.</p>
<div id="3991e099" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestRegressor</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error, mean_absolute_error, r2_score</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="b670a4d9" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">"Exam_Score ~ Hours_Studied + Attendance"</span>, data<span class="op">=</span>data).fit()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:             Exam_Score   R-squared:                       0.541
Model:                            OLS   Adj. R-squared:                  0.541
Method:                 Least Squares   F-statistic:                     3896.
Date:                Wed, 03 Dec 2025   Prob (F-statistic):               0.00
Time:                        11:46:22   Log-Likelihood:                -15776.
No. Observations:                6607   AIC:                         3.156e+04
Df Residuals:                    6604   BIC:                         3.158e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P&gt;|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        45.6042      0.252    180.743      0.000      45.110      46.099
Hours_Studied     0.2931      0.005     54.140      0.000       0.282       0.304
Attendance        0.1973      0.003     70.252      0.000       0.192       0.203
==============================================================================
Omnibus:                     7183.361   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           768940.589
Skew:                           5.425   Prob(JB):                         0.00
Kurtosis:                      54.725   Cond. No.                         648.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Based off the available variables, hours studied and attendance seem like they would have the strongest corelation to exam scores. After making a model with only these variables, we see that the explained variation in exam score is 54.1%. Both variables are significant and have a positive impact on exam score.</p>
<p>It is estimated that for each hour studied, a students exam score will increase by 0.29. For each additional hour in class, a students score rises by 0.19 on average.</p>
<div id="4500b96c" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">"Exam_Score ~ Hours_Studied + Attendance + Tutoring_Sessions + Previous_Scores + C(Gender)"</span>, data<span class="op">=</span>data).fit()</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:             Exam_Score   R-squared:                       0.597
Model:                            OLS   Adj. R-squared:                  0.596
Method:                 Least Squares   F-statistic:                     1954.
Date:                Wed, 03 Dec 2025   Prob (F-statistic):               0.00
Time:                        11:46:22   Log-Likelihood:                -15350.
No. Observations:                6607   AIC:                         3.071e+04
Df Residuals:                    6601   BIC:                         3.075e+04
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P&gt;|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            41.2666      0.290    142.166      0.000      40.698      41.836
C(Gender)[T.Male]    -0.0313      0.062     -0.508      0.611      -0.152       0.089
Hours_Studied         0.2916      0.005     57.431      0.000       0.282       0.302
Attendance            0.1977      0.003     75.062      0.000       0.193       0.203
Tutoring_Sessions     0.4958      0.025     20.061      0.000       0.447       0.544
Previous_Scores       0.0480      0.002     22.739      0.000       0.044       0.052
==============================================================================
Omnibus:                     8049.633   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1236152.329
Skew:                           6.526   Prob(JB):                         0.00
Kurtosis:                      68.726   Cond. No.                     1.07e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.07e+03. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<p>Adding more seemingly strong predictors, the R squared only increased by 5%. This suggests the addition of gender, tutoring, and previous scores does not improve the model tremendously.</p>
<p>We do get one negative coefficient for being male, suggesting that men score lower than women on average. However, this is not statistically significant.</p>
<div id="35b1be40" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Exam_Score ~ Hours_Studied + Attendance + Parental_Involvement + "</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Access_to_Resources + Extracurricular_Activities + Sleep_Hours + "</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Previous_Scores + Motivation_Level + Internet_Access + Tutoring_Sessions + "</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Family_Income + Teacher_Quality + C(School_Type) + Peer_Influence + "</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Physical_Activity + C(Learning_Disabilities) + C(Parental_Education_Level) + "</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Distance_from_Home + C(Gender)"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>data</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>).fit()</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:             Exam_Score   R-squared:                       0.722
Model:                            OLS   Adj. R-squared:                  0.720
Method:                 Least Squares   F-statistic:                     609.8
Date:                Wed, 03 Dec 2025   Prob (F-statistic):               0.00
Time:                        11:46:22   Log-Likelihood:                -13675.
No. Observations:                6378   AIC:                         2.741e+04
Df Residuals:                    6350   BIC:                         2.759e+04
Df Model:                          27                                         
Covariance Type:            nonrobust                                         
===============================================================================================================
                                                  coef    std err          t      P&gt;|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------
Intercept                                      41.8286      0.338    123.710      0.000      41.166      42.491
Parental_Involvement[T.Low]                    -1.9829      0.075    -26.309      0.000      -2.131      -1.835
Parental_Involvement[T.Medium]                 -1.0624      0.061    -17.557      0.000      -1.181      -0.944
Access_to_Resources[T.Low]                     -2.0633      0.075    -27.469      0.000      -2.211      -1.916
Access_to_Resources[T.Medium]                  -1.0096      0.060    -16.807      0.000      -1.127      -0.892
Extracurricular_Activities[T.Yes]               0.5620      0.053     10.615      0.000       0.458       0.666
Motivation_Level[T.Low]                        -1.0620      0.075    -14.101      0.000      -1.210      -0.914
Motivation_Level[T.Medium]                     -0.5423      0.069     -7.916      0.000      -0.677      -0.408
Internet_Access[T.Yes]                          0.9247      0.098      9.442      0.000       0.733       1.117
Family_Income[T.Low]                           -1.0856      0.072    -15.115      0.000      -1.226      -0.945
Family_Income[T.Medium]                        -0.5906      0.072     -8.210      0.000      -0.732      -0.450
Teacher_Quality[T.Low]                         -1.0575      0.094    -11.207      0.000      -1.242      -0.873
Teacher_Quality[T.Medium]                      -0.5490      0.058     -9.453      0.000      -0.663      -0.435
C(School_Type)[T.Public]                        0.0327      0.056      0.579      0.563      -0.078       0.143
Peer_Influence[T.Neutral]                       0.5222      0.070      7.415      0.000       0.384       0.660
Peer_Influence[T.Positive]                      1.0270      0.070     14.653      0.000       0.890       1.164
C(Learning_Disabilities)[T.Yes]                -0.8538      0.085    -10.074      0.000      -1.020      -0.688
C(Parental_Education_Level)[T.High School]     -0.4858      0.060     -8.119      0.000      -0.603      -0.369
C(Parental_Education_Level)[T.Postgraduate]     0.5027      0.075      6.734      0.000       0.356       0.649
Distance_from_Home[T.Moderate]                  0.3879      0.095      4.098      0.000       0.202       0.574
Distance_from_Home[T.Near]                      0.9077      0.089     10.225      0.000       0.734       1.082
C(Gender)[T.Male]                              -0.0422      0.053     -0.802      0.422      -0.145       0.061
Hours_Studied                                   0.2949      0.004     68.009      0.000       0.286       0.303
Attendance                                      0.1988      0.002     88.363      0.000       0.194       0.203
Sleep_Hours                                    -0.0020      0.018     -0.112      0.911      -0.037       0.033
Previous_Scores                                 0.0489      0.002     27.071      0.000       0.045       0.052
Tutoring_Sessions                               0.4982      0.021     23.699      0.000       0.457       0.539
Physical_Activity                               0.1867      0.025      7.385      0.000       0.137       0.236
==============================================================================
Omnibus:                    10556.728   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          5019643.307
Skew:                          11.388   Prob(JB):                         0.00
Kurtosis:                     138.535   Cond. No.                     1.49e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.49e+03. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<p>Using all the variables in the dataset has the highest R squared of the models created thus far. 72.2% of variation in exam scores can be explained when including all of the available variables. Only a few variables are not regarded as statistically significant and these include medium teacher quality, being male, and sleep hours.</p>
<p>The metric with the greatest quantitative impact on exam score is low access to resources. Students with low access to resources are expected to score 2 points lower than a student with all other similar conditions. The second greatest impact is positive peer influence. This suggests that students in a supportive student environment tend to score 1 point higher on the exam than students who are not in a positive environment. This is an interesting way to see how the energy and mindset of those around you impact your success.</p>
</section>
<section id="predicting-exam-score" class="level2">
<h2 class="anchored" data-anchor-id="predicting-exam-score">Predicting Exam Score</h2>
<p>I am using Random Forrest Regression to predict a students exam score based on the data. Since there are a number of categorical variables I used get_dummies to convert them into usable categical numbers. Further, I broke the data into a train and test set to fit a model to the training data then evaluate its performance on the test data. Finally, I computed performance metrics to understand how well the model does.</p>
<div id="9fcefe8c" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.get_dummies(data, drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df.drop(<span class="st">"Exam_Score"</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">"Exam_Score"</span>]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>rf <span class="op">=</span> RandomForestRegressor(n_estimators<span class="op">=</span><span class="dv">500</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>rf.fit(X_train, y_train)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>preds <span class="op">=</span> rf.predict(X_test)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> mean_squared_error(y_test, preds, squared<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>mae <span class="op">=</span> mean_absolute_error(y_test, preds)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> r2_score(y_test, preds)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"RMSE:"</span>, rmse)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MAE:"</span>, mae)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"R²:"</span>, r2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>RMSE: 2.225020452743883
MAE: 1.175018154311649
R²: 0.6497565877666611</code></pre>
</div>
</div>
<div id="14b82ae8" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>,<span class="dv">6</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>plt.scatter(y_test, preds, alpha<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>plt.plot([y_test.<span class="bu">min</span>(), y_test.<span class="bu">max</span>()], [y_test.<span class="bu">min</span>(), y_test.<span class="bu">max</span>()], <span class="st">'--'</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Actual Exam Score"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Predicted Exam Score"</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Actual vs Predicted Exam Scores"</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="DW_Final_files/figure-html/cell-13-output-1.png" width="530" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The models performance is moderately strong in its ability to predict exam scores. The RMSE expresses that the models predictions on average differ from the true score by 2.2 points. This is a very small margin.</p>
<p>The R square reflects that 64.9% of variation in exam scores can be explained by the model. This is a good score but could be stronger.</p>
<p>Overall, this model does a decent job predicting exam score. It would be interesting to see how adding variables like previous experience in the subject or motivation impact scores. Motivation could be measured by: whether or not the student is trying to find a job, whether they plan on pursuing a career in that subject, etc.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>